### ISSUE TITLE
Please help me with this issue

### ISSUE THREAD

**Issue by pavankumarreddysama** [iliran11/facebook-login-redux-react#9]
Log on to Facebook is displaying user details on same page . i want to show the user details on a new page..can u help me with that

**Comment by iliran11** [comment]
Hey,
Please share some code and give more details about the problems you have encountered.

**Comment by pavankumarreddysama** [comment]
I am new to reactjs and redux . After logon to facebook , ur displaying the details on same page and logout button on same page . My requirement is After logon to Facebook ,it should redirect to some page(profile) and display user details and should provide logout button on that profile page..can u please help me with that
